import type { ChangeClass, ServerSettings } from "./types";
import type { FieldMeta } from "./field-meta";
import { DEFAULT_CLIENT, DEFAULT_LANGUAGE_SERVER, DEFAULT_RAW, DEFAULT_SERVER, } from "./defaults";

const serverField = ( key: keyof ServerSettings, title: string, description: string, type: FieldMeta["type"], defaultValue: unknown, changeClass: ChangeClass, extra?: Partial<FieldMeta> ): FieldMeta => ({
  key: `mmkit.server.${key}`,
  title,
  description,
  type,
  default: defaultValue,
  changeClass,
  category: "server",
  ...extra,
});

/**
 * Canonical VS Code property-sheet field registry.
 *
 * Synced to `package.json` → `contributes.configuration` by `scripts/sync-contributes.ts`.
 * User-facing copy lives here; runtime contracts live in {@link @mmkit/base}.
 */
export const FIELD_REGISTRY: FieldMeta[] = [
  {
    key: "mmkit.operationalMode",
    title: "Operational mode",
    description: "Whether mmkit manages a local cbserver, connects as a TCP client, or stays idle.",
    markdownDescription: [
      "Controls which state machines are active.",
      "",
      "- **none** — server and client managers stay disabled.",
      "- **internalServer** — mmkit supervises a local cbserver using **Server** settings.",
      "- **client** — mmkit connects to an existing cbserver using **Client** settings.",
    ].join("\n"),
    type: "string",
    default: DEFAULT_RAW.operationalMode,
    enum: ["none", "internalServer", "client"],
    enumDescriptions: [
      "No local server and no outbound client connection.",
      "Start and supervise a cbserver subprocess on this machine.",
      "Connect to a remote cbserver over TCP.",
    ],
    order: 0,
    changeClass: "cold",
    category: "general",
  },
  {
    key: "mmkit.traceLevel",
    title: "Trace level",
    description: "Minimum OTEL severity for MMKit Trace output.",
    markdownDescription: "Filters mmkit extension diagnostics. Does not change cbserver `-t` trace mode (see Server runtime settings when exposed).",
    type: "string",
    default: DEFAULT_RAW.traceLevel,
    enum: ["trace", "debug", "info", "warn", "error", "off"],
    order: 1,
    changeClass: "hot",
    category: "general",
  },
  {
    key: "mmkit.languageServer.trace",
    title: "LSP trace",
    description: "Trace LSP messages to the MMKit Trace output channel.",
    type: "string",
    default: DEFAULT_LANGUAGE_SERVER.trace,
    enum: ["off", "messages", "verbose"],
    enumDescriptions: [
      "No LSP logging.",
      "Log message type and method name only.",
      "Log full JSON-RPC payloads.",
    ],
    order: 2,
    changeClass: "hot",
    category: "general",
  },
  {
    key: "mmkit.languageServer.lspPort",
    title: "LSP TCP port",
    description: "Host TCP port for the mmkit language server.",
    markdownDescription: "Port bound on `127.0.0.1` for the language server protocol endpoint.",
    type: "number",
    default: DEFAULT_LANGUAGE_SERVER.lspPort,
    order: 3,
    changeClass: "warm",
    category: "general",
  },
  {
    key: "mmkit.languageServer.httpPort",
    title: "HTTP port",
    description: "Host HTTP port for LSP health, readiness, metrics, and MCP (/mcp).",
    type: "number",
    default: DEFAULT_LANGUAGE_SERVER.httpPort,
    order: 4,
    changeClass: "warm",
    category: "general",
  },
  serverField( "launchKind", "Launch method", "Run cbserver as a local binary or inside Docker.", "string", DEFAULT_SERVER.launchKind, "cold", { enum: ["executable", "docker"], enumDescriptions: ["Spawn `cbserver` on the host PATH.", "Run cbserver in a container (future)."], order: 0, } ),
  serverField( "executablePath", "cbserver executable path", "Path to the cbserver binary.", "string", DEFAULT_SERVER.executablePath, "warm", { markdownDescription: "Absolute path or name resolved via `PATH`. Used when launch method is **executable**.", order: 1, } ),
  serverField("dockerImage", "Docker image", "Container image reference for Docker launch.", "string", DEFAULT_SERVER.dockerImage, "warm", { order: 2 }),
  serverField("dockerContainerName", "Docker container name", "Fixed name for the cbserver container.", "string", DEFAULT_SERVER.dockerContainerName, "warm", { order: 3 }),
  serverField("dockerExtraRunArgs", "Extra Docker run arguments", "Additional `docker run` arguments.", "array", DEFAULT_SERVER.dockerExtraRunArgs, "warm", { order: 4 }),
  serverField( "dataDir", "Data directory", "Base directory for mmkit-owned cbserver data.", "string", DEFAULT_SERVER.dataDir, "warm", { markdownDescription: "Default `~/.mmkit`. Expanded at launch; subdirectories derive database and temp paths when left empty.", scope: "application", order: 10, } ),
  serverField( "port", "TCP port", "Port cbserver listens on.", "number", DEFAULT_SERVER.port, "warm", { markdownDescription: "Maps to cbserver `-p` / `CB_PORTNR` (`2000`–`65535`).", order: 11, } ),
  serverField( "updateMode", "Update mode", "Database update persistency.", "string", DEFAULT_SERVER.updateMode, "warm", { enum: ["persistent", "nonpersistent"], enumDescriptions: ["Keep tells across restarts.", "Ephemeral session database under `tmpDir`."], order: 12, } ),
  serverField( "databasePath", "Database directory (-d)", "Persistent database directory.", "string", DEFAULT_SERVER.databasePath, "warm", { markdownDescription: "Empty = unset. Knowledge-base files only (not module save/views).", order: 20, } ),
  serverField( "databaseAllPath", "Workspace database (-db)", "Combined database workspace path.", "string", DEFAULT_SERVER.databaseAllPath, "warm", { markdownDescription: "Empty → `${dataDir}/workspace` when persistent and no `-d`/`-new` set.", order: 21, } ),
  serverField("newDatabasePath", "New database (-new)", "Create a new database at this path on start.", "string", DEFAULT_SERVER.newDatabasePath, "warm", { order: 22 }),
  serverField("resetOnStart", "Reset database on start", "Use `-new` instead of `-d` for `databasePath`.", "boolean", DEFAULT_SERVER.resetOnStart, "warm", { order: 23 }),
  serverField( "tmpDir", "Temporary directory", "TMPDIR for nonpersistent session copies.", "string", DEFAULT_SERVER.tmpDir, "warm", { markdownDescription: "Empty → `${dataDir}/tmp`.", order: 24, } ),
  serverField("loadDir", "Load directory", "Module load directory (`-load`).", "string", DEFAULT_SERVER.loadDir, "warm", { order: 25 }),
  serverField("saveDir", "Save directory", "Module save directory (`-save`).", "string", DEFAULT_SERVER.saveDir, "warm", { order: 26 }),
  serverField("viewsDir", "Views directory", "Materialized views directory (`-views`).", "string", DEFAULT_SERVER.viewsDir, "warm", { order: 27 }),
  serverField( "devCommand", "Dev command", "Override launch command for development.", "string", DEFAULT_SERVER.devCommand, "cold", { markdownDescription: "When non-empty, replaces `executablePath` in the subprocess launch spec.", order: 28, } ),
  serverField("extraArgs", "Extra arguments", "Additional cbserver CLI arguments.", "array", DEFAULT_SERVER.extraArgs, "warm", { order: 29 }),
  {
    key: "mmkit.client.host",
    title: "Server host",
    description: "Hostname or IP of the remote cbserver.",
    type: "string",
    default: DEFAULT_CLIENT.host,
    order: 0,
    changeClass: "warm",
    category: "client",
  },
  {
    key: "mmkit.client.port",
    title: "Server port",
    description: "TCP port of the remote cbserver.",
    type: "number",
    default: DEFAULT_CLIENT.port,
    order: 1,
    changeClass: "warm",
    category: "client",
  },
  {
    key: "mmkit.client.toolName",
    title: "Client tool name",
    description: "Tool name sent during ENROLL_ME.",
    type: "string",
    default: DEFAULT_CLIENT.toolName,
    order: 2,
    changeClass: "warm",
    category: "client",
  },
  {
    key: "mmkit.client.userName",
    title: "User name",
    description: "User name sent during ENROLL_ME.",
    type: "string",
    default: DEFAULT_CLIENT.userName,
    order: 3,
    changeClass: "warm",
    category: "client",
  },
  {
    key: "mmkit.client.connectTimeoutMs",
    title: "Connect timeout (ms)",
    description: "TCP connect and enroll timeout.",
    type: "number",
    default: DEFAULT_CLIENT.connectTimeoutMs,
    order: 4,
    changeClass: "warm",
    category: "client",
  },
  {
    key: "mmkit.client.autoConnect",
    title: "Auto-connect",
    description: "Connect automatically when operational mode is client.",
    type: "boolean",
    default: DEFAULT_CLIENT.autoConnect,
    order: 5,
    changeClass: "hot",
    category: "client",
  },
  {
    key: "mmkit.client.autoReconnect",
    title: "Auto-reconnect",
    description: "Reconnect after connection loss.",
    type: "boolean",
    default: DEFAULT_CLIENT.autoReconnect,
    order: 6,
    changeClass: "hot",
    category: "client",
  },
  {
    key: "mmkit.client.reconnectBackoffMs",
    title: "Reconnect backoff (ms)",
    description: "Delay before reconnect attempts.",
    type: "number",
    default: DEFAULT_CLIENT.reconnectBackoffMs,
    order: 7,
    changeClass: "warm",
    category: "client",
  },
];
