extensions:
  health_check:
    endpoint: 0.0.0.0:13133

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"

processors:
  batch: {}

exporters:
  otlphttp/victoriametrics:
    endpoint: http://victoriametrics:8428/opentelemetry
    tls:
      insecure: true
  otlphttp/victorialogs:
    logs_endpoint: http://victorialogs:9428/insert/opentelemetry/v1/logs
    tls:
      insecure: true
  otlphttp/victoriatraces:
    traces_endpoint: http://victoriatraces:10428/insert/opentelemetry/v1/traces
    tls:
      insecure: true

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/victoriatraces]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/victoriametrics]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/victorialogs]
